### ISSUE TITLE
What's the context of phantom.callback?

### ISSUE THREAD

**Issue by rictorres** [sgentle/phantomjs-node#224]
Hi, I'm currently writing header/footer on each page using something like this:
```js
var phantom = require('node-phantom');
 
phantom.create(function (ph) {
	ph.createPage(function (page) {
		page.open("http://www.google.com", function (status) {
 
			var paperConfig = {
				format: 'A4',
				orientation: 'portrait',
				border: '1cm',
				header: {
					height: '1cm',
					contents: ph.callback(function(pageNum, numPages) {
						return '<h1>My Custom Header</h1>';
					})
				},
				footer: {
					height: '1cm',
					contents: ph.callback(function(pageNum, numPages) {
						return '<p>Page ' + pageNum + ' / ' + numPages + '</p>';
					})
				}
			};
 
			page.set('paperSize', paperConfig, function() {
				// render to pdf
				page.render('path/to/file.pdf', function() {
					page.close();
					ph.exit();
				});
			});
		});
	});
});
```

Inside `ph.callback` I need to pretty print today's date based on a pre-defined format (user settings).
Is there a way to achieve this? How can I pass data to this callback?

Thanks a lot :)

**Comment by bright-sea** [comment]
+1

This is a great question. It is quite important to customize header and footer. Anybody has any idea?

**Comment by kubosador** [comment]
+1
I completely agree ! This is not possible to customize header/footer.

**Comment by chk-** [comment]
I had similar needs and worked out this solution. (I needed to add an image from local path.) Please try the following.

The fact is that Phantom executes header and footer functions in it's own scope, so dynamic paths are impossible. The solution is a constructed function, resolved in this scope:

```
var createHeader = new Function('pageNum', 'numPages', 'return \'<div style="position:absolute; top:0; width:100%; height:4.5cm; margin:0; margin-left:-0.22cm; padding:0.25cm; overflow:visible;">'
                          +'<img src="file://'+ path.resolve(srv.options.dat_path, 'print', 'my-local-header-pic.png') +'" style="width:100%;" alt="header" />'
                          +'<span style="font-family: Arial; font-size:20px; font-weight: bold; position:absolute; left:125; top:135;">MyCustomHeader</span>'
                          +'</div>\';');
```
Then add the constructed function this way:
```
var paperConfig = {
                format: 'A4',
                orientation: 'portrait',
                border: '1cm',
                header: {
                    height: '1cm',
                    contents: createHeader
                },
                footer: {
                    height: '1cm',
                    contents: ph.callback(function(pageNum, numPages) {
                        return '<p>Page ' + pageNum + ' / ' + numPages + '</p>';
                    })
                }
            };
```
I think, with this showcase it will be easy for you to add your custom data, formated date in your case.

**Comment by lathonez** [comment]
createHeader needs wrapping in `ph.callback`, took me too long to work out:

```
                header: {
                    height: '1cm',
                    contents: ph.callback(createHeader)
                },
```

**Comment by zgotts** [comment]
There still doesn't seem to be a clear answer to this question, even though it was closed.

I want to create a timestamp to go in the footer of my PDF. I want to pass timezone information that comes in from the client side into the footer generator function (the one passed to ph.callback). Despite numerous attempts, I can't seem to be able to successfully pass an argument into that function.

I created a closure that contains the timezone information and returns a function that takes pageNum and numPages as arguments, and then passed that closure to ph.callback, but the timestamp argument is still undefined.

`var moment = require('moment');
    var timestamp = moment().utcOffset(params.tzoffset).format('MM/DD/YY hh:mm A');

    var makeFooterFn = function (timestamp) {
        return function (pageNum, numPages) {
            return '<h1 style="padding: 0 30px; font-weight: normal; font-family: \'open sans\', Helvetica, Arial, sans-serif; font-size: 20px;">' +
                    'Created on ' + timestamp +
                    '<span style="float:right">Page ' + pageNum + '/' + numPages + '</span>' +
                    '</h1>';
        }
    };`

So I'm curious: 
1) What is the context of phantom.callback?
2) How do you pass a variable into the footer function in phantom.callback?

Thank you!

**Comment by jorisdesmedt** [comment]
The phantom callback function has its own context so you can't use local variables.

I use local variables by creating a function, stringify it and string replace the local variables.
Example:

`
function footer(title, date) {
  return function (pageNum, numPages) {
    var title='%TITLE%';
    var daterange = '%DATE%';
    var html = [
      '<table style="width: 100%; font-size: 14px; zoom: 0.5;font-family: "Lato", Helvetica, Arial, sans-serif;"><tr>',
      '<td style="text-align: left; width: 33%;">'+title+'</td>',
      '<td style="text-align: center; width: 34%;">'+daterange+'</td>',
    ];
    if(numPages > 0) {
      html.push('<td style="text-align: right; width: 33%;">'+pageNum+ ' / '+numPages+'</td>');
    }
    html.push('</tr></table>');
    return html.join('');
  }
  .toString()
  .replace(/%TITLE%/, title)
  .replace(/%DATE%/, date);
}
`

**Comment by cristianszwarc** [comment]
thanks @jorisdesmedt 

my two cents.. (be aware this is evaluating code!)

```
// dynamic creation of a function to be used with phantomjs (be aware of eval!)
function customFooter(custom) {
    custom = custom.replace(/%pageNum%/g, '\' + pageNum + \'');
    custom = custom.replace(/%numPages%/g, '\' + numPages + \'');
    return new Function('pageNum', 'numPages', 'return \'' + custom + '\';');
}
...

// use as:
paperSizeAndFooter.footer = {
    ...
    contents: phInstance.callback(customFooter('Page %pageNum% of %numPages%')),
    ...
};

```
